openapi: 3.0.0
info:
  title: Blog and Post API
  version: 1.0.0
  description: Blogger platform API documentation

tags:
  - name: Auth
  - name: Blogs
  - name: Comments
  - name: Posts
  - name: Testing
  - name: Users
