paths:
  /auth/login:
    post:
      summary: Try login user to the system
      tags: [ Auth ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInputModel'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginInputModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginInputModel'
      responses:
        200:
          description: Returns JWT-token
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/LoginSuccessViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessViewModel'
        400:
          description: If the inputModel has incorrect values
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/APIErrorResult'
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResult'
            text/json:
              schema:
                $ref: '#/components/schemas/APIErrorResult'
        401: 
          description: If the password or login is wrong
  /auth/me:
    get:
      summary: Get information about current user
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MeViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/MeViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/MeViewModel'
        401:
          description: Unauthorized

components:
  schemas:
    APIErrorResult:
      type: object
      properties:
        errorsMessages:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/FieldError'
    
    FieldError:
      type: object
      properties:
        message:
          type: string
          nullable: true
          description: "Message with error explanation for certain field"
        field:
          type: string
          nullable: true
          description: "What field/property of input model has error"
    
    LoginInputModel:
      type: object
      required:
        - loginOrEmail
        - password
      properties:
        loginOrEmail:
          type: string
        password:
          type: string
    
    LoginSuccessViewModel:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
    
    MeViewModel:
      type: object
      required:
        - email
        - login
        - userId
      properties:
        email:
          type: string
        login:
          type: string
        userId:
          type: string
